version: '2'
services:
    database:
        image: postgres:10
        environment:
            - "POSTGRES_USER=root"
            - "POSTGRES_PASSWORD=111"
            - "POSTGRES_DB=seller_center"
        ports:
            - "5432:5432"
